### PR TITLE
Feature Request: Optionally use "composer" instead of "artist"

### PR DESCRIPTION
**Pull request by s-scherrer**
I just found this MPD client today, and it really seems to be the best out there currently for my purposes, thanks a lot.

However, since I'm mostly listening to classical music it would be nice to have the option to use the "composer" tag instead of "artist" or "albumartist". I made a draft where I just added an option for composer, similar to the album artist option.

I didn't manage to install and test it on my system unfortunately, so I have no idea if it is as easy as in the draft. Would you be open to support such a feature?

### CODE REVIEW

**Comment by SoongNoonien** [comment]
Hi!
Thanks for your contribution.
> Would you be open to support such a feature?

Since I'm not listening that much to classical music it has a very low priority for me. And I'm not sure if I can maintain a player which tries to support classical music. And I think supporting classical music in all ways is definitely a non trivial task. But I wouldn't say I'm completely against such a feature.

> I didn't manage to install and test it on my system unfortunately, so I have no idea if it is as easy as in the draft.

Sadly not. This would require a complete internal restructuring of the browser. I also would need to figure out a sane logic of how this would behave compared to "artist" or "albumartist".
Your current patch sadly does effectively nothing but crashing the settings window since you forgot to add the regarding key to the settings schema.

**Comment by dgcampea** [comment]
This feature would fit best if the <all genres> button gets modified to allow for other tags to be used. (maybe show a list of tags that can be used)

**Comment by s-scherrer** [comment]
> And I'm not sure if I can maintain a player which tries to support classical music. And I think supporting classical music in all ways is definitely a non trivial task.

Sorting/grouping by composer would be enough, at least for me.

I now managed to install it (didn't have `intltool` and had some problems with the copying of the schema file) and test it. It seems to work well enough for me (with the fix in the schema file):

Screenshot from 2021-07-20 21-45-24

Do you have an idea where in the browser further changes are required?

Also, I ran into an issue with a track in my music library that had the tag "disc": "1/1" , which I believe is unrelated to my changes, and for which I also pushed a fix. It worked on the flatpak version with the same library though, so I assume it was introduced recently.

@dgcampea: Yes, that would probably be the best solution.

**Comment by SoongNoonien** [comment]
> Do you have an idea where in the browser further changes are required?

Yes, I try to list them (using line numbers from master):

- `ArtistWindow._refresh` line 2183
- `Browser._back_to_current_album` line 2567
- `CoverEventBox._on_button_press_event` line 2764

They all use the normal "artist" tag as hard coded fallback. Also the `AlbumDialog` should be reworked, starting in line 1788. But this is debatable. `ArtistWindow` is still showing "all artists" as first entry which is now wrong. Btw its name is also a bit confusing now. The function `Client.get_albums` also uses hard coded "artist" (as dict key) to represent either "artist" or "albumartist".
In the settings it is currently possible to enable "composer" and "albumartist" at the same time which is clearly confusing. These should be at least radio buttons. But a combo box would be a better choice I think. If it's possible the settings schema should use something like an enum rather than booleans. When the browser can group by composer it should also be possible to show a composer column in the playlist, shouldn't it?

**Comment by s-scherrer** [comment]
Thanks for the suggestions. I think I could try to work on this, if that's okay for you, although I don't have that much time in the next 2 weeks, so it will take some time.

**Comment by s-scherrer** [comment]
I changed the settings to use a ComboBox:

Screenshot from 2021-08-01 17-49-56

I also changed  the lines you mentioned where "artist" was used as a fallback value to just use "" in case the tag is not available, although I'm not sure if that's good behaviour. Even when using "composer" as artist type, I think it's sane to use the value for "artist" as fallback in case "composer" is not available. What is your opinion on this?

As requeisted, I added an option to add a "Composer" column in the playlist, and changed "all artists" to "all <artist-type>". I did not change anything in `Client.get_albums` yet. Is the "artist" dict key displayed somewhere? To me it looks like the key is only used internally.

I think there's probably also some translations to change, right?

**Comment by SoongNoonien** [comment]
> Even when using "composer" as artist type, I think it's sane to use the value for "artist" as fallback in case "composer" is not available. What is your opinion on this?

I don't think this makes any sense. When requesting all "albumartist" tags from MPD it will fall back to "artist" if a file does not have a valid "albumartist" tag. Therefore the "artist" tag of files with no "albumartist" set will appear in the artist list even when "albumartist" is used by mpdevil. But when requesting all "composer" tags from MPD it will not fall back to any other tag especially not "artist". So using "artist" as a fallback here wont work since the composer list will only contain composers and no artists. Removing the fallback is also not the right choice since it is still needed when the "albumartist" tag is used.

> Is the "artist" dict key displayed somewhere? To me it looks like the key is only used internally.

Yes, it is mostly internal but it is displayed in the album list when using "all artist" (or "all composers").

> I think there's probably also some translations to change, right?

Yes, but this is currently not needed. I usually update the translations right before a new release.

Some general thoughts/bugs: When the "composer" column is shown the playlist crashes when encountering files without a "composer" tag. The "artist-type" key currently allows any string as value. By using the "<choices></choices>" tag this can be improved a bit but the documentation of these settings schemas sadly isn't that good. I think "Artist tag to use for grouping:" is not the best choice. I'm also not sure but I'd suggest something like "Group albums by:". And this setting definitely shouldn't be in between two checkbuttons. It either as to go first or last it this block. Switching the combobox currently doesn't update the "all artists" string, when I switch from "composer" to "albumartist" it still shows "all composers". The whole program needs to be restarted to fix this. I think "albumartist" is no real word (it's just a tag name) so displaying "all albumartists" is not right and not translation friendly.

I hope you see now that this whole thing is not trivial. I still don't have a complete concept of how this can be implemented in a nice and logical way.

**Comment by s-scherrer** [comment]
> I hope you see now that this whole thing is not trivial. I still don't have a complete concept of how this can be implemented in a nice and logical way.

I think the main issue is handling files where no composer is given, right? From a user perspective, it would make sense to me to replace the composer with the artist in these cases, although an empty string is also fine, since I think most users using this feature have correctly tagged composers anyway.

To me it would make most sense to "normalise" the songs by wrapping calls to `MPDClient.find`, `MPDClient.currentsong`, etc. with something that makes sure that the "composer" tag is set, e.g.:
```
class Client(MPDClient):

    def find(self, *args):
        songs = super().find(*args)
        for song in songs:
            if "composer" not in song:
                song["composer"] = ""
        return songs
```

Does the general idea make sense to you?

The other issues are mainly small things, I believe, that I will address later (it's a draft PR, after all).

**Comment by SoongNoonien** [comment]
> I think the main issue is handling files where no composer is given, right?

No, that's relatively easy to fix. We only need to extend the `base_song` dict in `ClientHelper`. The overall concept is the main problem. Mpdevil should be a simple client and this pull request makes it definitely way more complex. Currently mpdevil always shows artists and their albums (the albumartist tag is only used for compilation). Which hopefully makes is clearly structured and simple. When I merge this request it suddenly also supports showing composers and their albums. But when supporting composers why not also support conductors or even all available tags? And what about people listening to "pop" and classical music? They probably want to change the group tag on the fly without going to the settings just like they now can filter by another genre. So the clear concept is gone. I hope you can understand that these conceptional questions are not that easy and yet very important.

> Does the general idea make sense to you?

An empty string would be an appropriate choice. But no wrapping is needed (see above comment according `ClientHelper`).

> The other issues are mainly small things, I believe, that I will address later (it's a draft PR, after all).

Sure, take your time. As I said earlier this pull request has a low priority for me.

**Comment by s-scherrer** [comment]
I'm not sure if I understand you correctly, so you want to have an overall concept of how the feature is used, not how it's implemented?

The concept I had in mind is to really just replace artist with composer as an optional feature. I don't think mpdevil should support some mix of composer and artist, or provide the option to change on the fly between artist and composer. As you say, this just makes it a lot more complicated, and the nice thing about mpdevil is the simple UI.
Other tags like "conductor" might be possible, but on the one hand it's even more niche than using composer, and on the other hand it would be very easy to add if someone would request it.

Is that concept okay for you to support in mpdevil or rather not?

**Comment by SoongNoonien** [comment]
> I'm not sure if I understand you correctly, so you want to have an overall concept of how the feature is used, not how it's implemented?

Yes.

> Is that concept okay for you to support in mpdevil or rather not?

Well, that is the problem. I'm not yet sure how it should behave. Two things are still a bit inconsistent in the current concept of this draft. The genre filter is more or less useless when the composers are shown, because genres other than "classical" probably don't have any composers. And the albums are strictly grouped by composer. Which will split compilations with multiple composers. But you don't have to fix these neither immediately nor at all, as you said it's still a draft. And I will also look into it a bit deeper but not right now.

**Comment by dgcampea** [comment]
Perhaps something like [MPD filter expressions](https://mpd.readthedocs.io/en/latest/protocol.html#filters) is what you'd want here. (if fallbacks aren't ideal)
IIRC, the search box doesn't support them but it shouldn't be too hard to add them.
Alternatively, some sort of "user defined search criteria" could be used in the ComboBox you're using [here](https://user-images.githubusercontent.com/24706421/127777480-e19fd84e-9917-4049-988c-26605868fcde.png) and a new "tab" next to "Playlists" named "Custom search criteria" where you could add and name your custom _MPD filter expressions_.

Incidentally, is there some sort of manual that explains the GTK/UI jargon? I'm unfamiliar with GTK/UI programming in general and being unable to describe the components by their name is probably adding confusion to the discussion.

**Comment by SoongNoonien** [comment]
> Incidentally, is there some sort of manual that explains the GTK/UI jargon? I'm unfamiliar with GTK/UI programming in general and being unable to describe the components by their name is probably adding confusion to the discussion.

Yes, a small intro can be found here: https://python-gtk-3-tutorial.readthedocs.io/en/latest/ and the main documentation I'm using is this: https://lazka.github.io/pgi-docs/Gtk-3.0/classes.html.

**Comment by SoongNoonien** [comment]
Hi!
I took a closer look and decided to not merge this request. Furthermore I wont support classical music at all. I think this would require another player optimized for classical music. As I mentioned before I'm not able to test these functionalities but I like mpdevil to be completely testable and maintainable just by me. This also helps to keep the complexity at a decent level.

I hope you understand and didn't spend too much time on this.

**Comment by s-scherrer** [comment]
Sure, that's fine, thanks for letting me know.

**Pull request closed without merging**
